version: '3'

networks:
  app:
    driver: bridge

services:
 postgres:
    image: postgres:11.1
    restart: on-failure
    environment:
      POSTGRES_USER: guard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_guard
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app
